### ISSUE TITLE
Stepperature missing steps

### ISSUE THREAD

**Issue by ghost** [rekursiv/stepperature#2]
Finally after many years got around to using this ver 2 board.
2 issues: 
1 . very slow rotation produces nothing.. i am aware of why but have to be careful in my app to avoid min speed.
2. board severely loads down the stepper, the coggging is a real proble in my app - need to rotate easily.
3. after exhaustive tests found the output inconsistent (avoiding very slow rotations.).. the test  motor (driven stepper motor) shaft ends up not where it should be.. Disappointed.
Note if U have a better version, I cant find where to buy now!

**Comment by ghost** [comment]
please advise re the above, cannot find how to buy ..

**Comment by ghost** [comment]
uhem, it appears stepper motor drive not up to par, thus missing steps appeared. So Stepperature redeemed indeed. However the loading problem remains.
No responses tho re where to buy..PLEASE advise

**Comment by rekursiv** [comment]
Sorry, ProtoPlant has not released any improved version, and Stepperature is no longer for sale.  Stepperature was designed to be driven "by hand" for the purpose of human-machine interface.  The "loading" is by design, to keep it from being accidentally activated.  If you're driving Stepperature with another motor, I would recommend an optical encoder for that application.
